apiVersion: v1
kind: Service
metadata:
  name: my-node-app-service
  labels:
    app: my-app
spec:
  selector:
    app: node-app
  ports:
    - name: http
      port: 8080  # Service port
      targetPort: 3000  # Container port
  type: LoadBalancer  # Change to NodePort or LoadBalancer if needed
