wordpress:
  image: wordpress:6.4
  replicas: 1
  service:
    type: NodePort
    port: 80
  env:
    WORDPRESS_DB_HOST: mysql
    WORDPRESS_DB_USER: admin                
    WORDPRESS_DB_PASSWORD: admin        
    WORDPRESS_DB_NAME: wordpress

mysql:
  image: mysql:5.7
  rootPassword: rootpass
  database: wordpress
  user: admin                   
  password: admin              
  service:
    port: 3306
