apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-2
spec:
  containers:
  - name: demo-container
    image: nginx
    # Inject environment variables from a Secret
    envFrom:
    - secretRef:
       name: docker-secret    # Name of the Secret containing environment variables

---

apiVersion: v1
kind: Pod
metadata:
  name: private-pod
spec:
  containers:
    - name: my-app
      image: my-registry.example:5000/my-app:latest    # Private registry image
  # Pull images from a private Docker registry using a Secret
  imagePullSecrets:
    - name: docker-secret   # Secret storing Docker registry credentials
