apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_ENV: "staging"
  APP_DEBUG: "true"
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-env-pod
spec:
  containers:
    - name: my-container
      image: nginx
      env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_ENV
        - name: APP_DEBUG
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_DEBUG
---
apiVersion: v1
kind: Pod
metadata:
  name: direct-env-pod
spec:
  containers:
    - name: my-container
      image: nginx
      env:
        - name: APP_ENV
          value: "production"
        - name: APP_DEBUG
          value: "false"
