apiVersion: v1                  # API version for Service
kind: Service                   # Specifies this is a Service resource
metadata:
  name: nginx-service           # Name of the Service
spec:
  selector:
    app: nginx                  # Targets pods with label 'app: nginx'
  ports:
    - protocol: TCP             # Protocol used by the service
      port: 80                  # Port exposed by the Service (ClusterIP)
      targetPort: 80            # Port on the Pod the traffic is forwarded to
  type: NodePort                # Service type that exposes the pod on a node's IP and a dynamic port
